services:
  postgresql:
    container_name: postgresql
    image: postgres
    environment:
      POSTGRES_USER: theanh
      POSTGRES_PASSWORD: theanh
      POSTGRES_DB: A159
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres:
